Remove-Item –path ./client –recurse
& java -jar swagger-codegen-cli-2.4.5.jar generate -i https://api.cloudmersive.com/swagger/api/ocr -l csharp -o client -c packageconfig.json
#(Get-Content ./client/src/api/ConvertDocumentApi.js).replace('var returnType = Object;', "var returnType = 'Blob';") | Set-Content ./client/src/api/ConvertDocumentApi.js
#(Get-Content ./client/src/api/ConvertWebApi.js).replace('var returnType = Object;', "var returnType = 'Blob';") | Set-Content ./client/src/api/ConvertWebApi.js









$csprojpath = Resolve-Path ./client/src/Cloudmersive.APIClient.NET.OCR/Cloudmersive.APIClient.NET.OCR.csproj
$csprojtestpath = Resolve-Path ./client/src/Cloudmersive.APIClient.NET.OCR.Test/Cloudmersive.APIClient.NET.OCR.Test.csproj
$nuspecpath = Resolve-Path ./client/src/Cloudmersive.APIClient.NET.OCR/Cloudmersive.APIClient.NET.OCR.nuspec
$slnpath = Resolve-Path ./client/Cloudmersive.APIClient.NET.OCR.sln


(Get-Content $nuspecpath).replace('<title>Swagger Library</title>', "<title>Cloudmersive OCR API Client</title><licenseUrl>https://www.apache.org/licenses/LICENSE-2.0.txt</licenseUrl>") | Set-Content $nuspecpath
(Get-Content $nuspecpath).replace('<authors>$author$</authors>', "<authors>Cloudmersive</authors>") | Set-Content $nuspecpath
(Get-Content $nuspecpath).replace('<owners>$author$</owners>', "<owners>Cloudmersive</owners>") | Set-Content $nuspecpath
(Get-Content $nuspecpath).replace('<description>A library generated from a Swagger doc</description>', "<description>The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.</description>") | Set-Content $nuspecpath
(Get-Content $nuspecpath).replace('<!-- Authors contain text that appears directly on the gallery -->', "<iconUrl>https://cloudmersive.com/images/cmsdk.png</iconUrl>") | Set-Content $nuspecpath
(Get-Content $nuspecpath).replace('<dependencies>', "<projectUrl>https://cloudmersive.com/ocr-api</projectUrl><dependencies>") | Set-Content $nuspecpath
(Get-Content '.\client\src\Cloudmersive.APIClient.NET.OCR\Client\Configuration.cs').replace('Timeout = 100000;', "Timeout = 900000;") | Set-Content '.\client\src\Cloudmersive.APIClient.NET.OCR\Client\Configuration.cs'





./nuget.exe restore $csprojpath -SolutionDirectory ./client

./nuget.exe restore $csprojtestpath -SolutionDirectory ./client

C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe $slnpath /t:rebuild 

./nuget.exe pack $csprojpath

(Get-Content ./client/README.md).replace(' automatically generated by the [Swagger Codegen](https://github.com/swagger-api/swagger-codegen) project', " for the [Cloudmersive OCR API](https://www.cloudmersive.com/ocr-api)") | Set-Content ./client/README.md

Copy-Item ./client/README.md ./README.md