/* 
 * ocrapi
 *
 * The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.OCR.Api;
using Cloudmersive.APIClient.NET.OCR.Model;
using Cloudmersive.APIClient.NET.OCR.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.OCR.Test
{
    /// <summary>
    ///  Class for testing BusinessCardRecognitionResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BusinessCardRecognitionResultTests
    {
        // TODO uncomment below to declare an instance variable for BusinessCardRecognitionResult
        //private BusinessCardRecognitionResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BusinessCardRecognitionResult
            //instance = new BusinessCardRecognitionResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BusinessCardRecognitionResult
        /// </summary>
        [Test]
        public void BusinessCardRecognitionResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BusinessCardRecognitionResult
            //Assert.IsInstanceOfType<BusinessCardRecognitionResult> (instance, "variable 'instance' is a BusinessCardRecognitionResult");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'PersonName'
        /// </summary>
        [Test]
        public void PersonNameTest()
        {
            // TODO unit test for the property 'PersonName'
        }
        /// <summary>
        /// Test the property 'PersonTitle'
        /// </summary>
        [Test]
        public void PersonTitleTest()
        {
            // TODO unit test for the property 'PersonTitle'
        }
        /// <summary>
        /// Test the property 'BusinessName'
        /// </summary>
        [Test]
        public void BusinessNameTest()
        {
            // TODO unit test for the property 'BusinessName'
        }
        /// <summary>
        /// Test the property 'AddressString'
        /// </summary>
        [Test]
        public void AddressStringTest()
        {
            // TODO unit test for the property 'AddressString'
        }
        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Test]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }
        /// <summary>
        /// Test the property 'EmailAddress'
        /// </summary>
        [Test]
        public void EmailAddressTest()
        {
            // TODO unit test for the property 'EmailAddress'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Test]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }

    }

}
