/* 
 * ocrapi
 *
 * The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.OCR.Api;
using Cloudmersive.APIClient.NET.OCR.Model;
using Cloudmersive.APIClient.NET.OCR.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.OCR.Test
{
    /// <summary>
    ///  Class for testing FormTableColumnDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FormTableColumnDefinitionTests
    {
        // TODO uncomment below to declare an instance variable for FormTableColumnDefinition
        //private FormTableColumnDefinition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FormTableColumnDefinition
            //instance = new FormTableColumnDefinition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FormTableColumnDefinition
        /// </summary>
        [Test]
        public void FormTableColumnDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FormTableColumnDefinition
            //Assert.IsInstanceOfType<FormTableColumnDefinition> (instance, "variable 'instance' is a FormTableColumnDefinition");
        }


        /// <summary>
        /// Test the property 'ColumnID'
        /// </summary>
        [Test]
        public void ColumnIDTest()
        {
            // TODO unit test for the property 'ColumnID'
        }
        /// <summary>
        /// Test the property 'TopAnchor'
        /// </summary>
        [Test]
        public void TopAnchorTest()
        {
            // TODO unit test for the property 'TopAnchor'
        }
        /// <summary>
        /// Test the property 'AnchorMode'
        /// </summary>
        [Test]
        public void AnchorModeTest()
        {
            // TODO unit test for the property 'AnchorMode'
        }
        /// <summary>
        /// Test the property 'DataType'
        /// </summary>
        [Test]
        public void DataTypeTest()
        {
            // TODO unit test for the property 'DataType'
        }
        /// <summary>
        /// Test the property 'MinimumCharacterCount'
        /// </summary>
        [Test]
        public void MinimumCharacterCountTest()
        {
            // TODO unit test for the property 'MinimumCharacterCount'
        }
        /// <summary>
        /// Test the property 'AllowNumericDigits'
        /// </summary>
        [Test]
        public void AllowNumericDigitsTest()
        {
            // TODO unit test for the property 'AllowNumericDigits'
        }

    }

}
