/* 
 * ocrapi
 *
 * The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.OCR.Api;
using Cloudmersive.APIClient.NET.OCR.Model;
using Cloudmersive.APIClient.NET.OCR.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.OCR.Test
{
    /// <summary>
    ///  Class for testing FormFieldDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FormFieldDefinitionTests
    {
        // TODO uncomment below to declare an instance variable for FormFieldDefinition
        //private FormFieldDefinition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FormFieldDefinition
            //instance = new FormFieldDefinition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FormFieldDefinition
        /// </summary>
        [Test]
        public void FormFieldDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FormFieldDefinition
            //Assert.IsInstanceOfType<FormFieldDefinition> (instance, "variable 'instance' is a FormFieldDefinition");
        }


        /// <summary>
        /// Test the property 'FieldID'
        /// </summary>
        [Test]
        public void FieldIDTest()
        {
            // TODO unit test for the property 'FieldID'
        }
        /// <summary>
        /// Test the property 'LeftAnchor'
        /// </summary>
        [Test]
        public void LeftAnchorTest()
        {
            // TODO unit test for the property 'LeftAnchor'
        }
        /// <summary>
        /// Test the property 'TopAnchor'
        /// </summary>
        [Test]
        public void TopAnchorTest()
        {
            // TODO unit test for the property 'TopAnchor'
        }
        /// <summary>
        /// Test the property 'AnchorMode'
        /// </summary>
        [Test]
        public void AnchorModeTest()
        {
            // TODO unit test for the property 'AnchorMode'
        }
        /// <summary>
        /// Test the property 'DataType'
        /// </summary>
        [Test]
        public void DataTypeTest()
        {
            // TODO unit test for the property 'DataType'
        }
        /// <summary>
        /// Test the property 'TargetDigitCount'
        /// </summary>
        [Test]
        public void TargetDigitCountTest()
        {
            // TODO unit test for the property 'TargetDigitCount'
        }
        /// <summary>
        /// Test the property 'MinimumCharacterCount'
        /// </summary>
        [Test]
        public void MinimumCharacterCountTest()
        {
            // TODO unit test for the property 'MinimumCharacterCount'
        }
        /// <summary>
        /// Test the property 'AllowNumericDigits'
        /// </summary>
        [Test]
        public void AllowNumericDigitsTest()
        {
            // TODO unit test for the property 'AllowNumericDigits'
        }
        /// <summary>
        /// Test the property 'VerticalAlignmentType'
        /// </summary>
        [Test]
        public void VerticalAlignmentTypeTest()
        {
            // TODO unit test for the property 'VerticalAlignmentType'
        }
        /// <summary>
        /// Test the property 'HorizontalAlignmentType'
        /// </summary>
        [Test]
        public void HorizontalAlignmentTypeTest()
        {
            // TODO unit test for the property 'HorizontalAlignmentType'
        }
        /// <summary>
        /// Test the property 'TargetFieldWidthRelative'
        /// </summary>
        [Test]
        public void TargetFieldWidthRelativeTest()
        {
            // TODO unit test for the property 'TargetFieldWidthRelative'
        }
        /// <summary>
        /// Test the property 'TargetFieldHeightRelative'
        /// </summary>
        [Test]
        public void TargetFieldHeightRelativeTest()
        {
            // TODO unit test for the property 'TargetFieldHeightRelative'
        }
        /// <summary>
        /// Test the property 'TargetFieldHorizontalAdjustment'
        /// </summary>
        [Test]
        public void TargetFieldHorizontalAdjustmentTest()
        {
            // TODO unit test for the property 'TargetFieldHorizontalAdjustment'
        }
        /// <summary>
        /// Test the property 'TargetFieldVerticalAdjustment'
        /// </summary>
        [Test]
        public void TargetFieldVerticalAdjustmentTest()
        {
            // TODO unit test for the property 'TargetFieldVerticalAdjustment'
        }
        /// <summary>
        /// Test the property 'Ignore'
        /// </summary>
        [Test]
        public void IgnoreTest()
        {
            // TODO unit test for the property 'Ignore'
        }

    }

}
