/* 
 * ocrapi
 *
 * The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.OCR.Api;
using Cloudmersive.APIClient.NET.OCR.Model;
using Cloudmersive.APIClient.NET.OCR.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.OCR.Test
{
    /// <summary>
    ///  Class for testing FormTableDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FormTableDefinitionTests
    {
        // TODO uncomment below to declare an instance variable for FormTableDefinition
        //private FormTableDefinition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FormTableDefinition
            //instance = new FormTableDefinition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FormTableDefinition
        /// </summary>
        [Test]
        public void FormTableDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FormTableDefinition
            //Assert.IsInstanceOfType<FormTableDefinition> (instance, "variable 'instance' is a FormTableDefinition");
        }


        /// <summary>
        /// Test the property 'TableID'
        /// </summary>
        [Test]
        public void TableIDTest()
        {
            // TODO unit test for the property 'TableID'
        }
        /// <summary>
        /// Test the property 'ColumnDefinitions'
        /// </summary>
        [Test]
        public void ColumnDefinitionsTest()
        {
            // TODO unit test for the property 'ColumnDefinitions'
        }
        /// <summary>
        /// Test the property 'TargetTableHeightRelative'
        /// </summary>
        [Test]
        public void TargetTableHeightRelativeTest()
        {
            // TODO unit test for the property 'TargetTableHeightRelative'
        }
        /// <summary>
        /// Test the property 'TargetRowHeightRelative'
        /// </summary>
        [Test]
        public void TargetRowHeightRelativeTest()
        {
            // TODO unit test for the property 'TargetRowHeightRelative'
        }

    }

}
