/* 
 * ocrapi
 *
 * The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.OCR.Api;
using Cloudmersive.APIClient.NET.OCR.Model;
using Cloudmersive.APIClient.NET.OCR.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.OCR.Test
{
    /// <summary>
    ///  Class for testing ImageToTextResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ImageToTextResponseTests
    {
        // TODO uncomment below to declare an instance variable for ImageToTextResponse
        //private ImageToTextResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ImageToTextResponse
            //instance = new ImageToTextResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ImageToTextResponse
        /// </summary>
        [Test]
        public void ImageToTextResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ImageToTextResponse
            //Assert.IsInstanceOfType<ImageToTextResponse> (instance, "variable 'instance' is a ImageToTextResponse");
        }


        /// <summary>
        /// Test the property 'MeanConfidenceLevel'
        /// </summary>
        [Test]
        public void MeanConfidenceLevelTest()
        {
            // TODO unit test for the property 'MeanConfidenceLevel'
        }
        /// <summary>
        /// Test the property 'TextResult'
        /// </summary>
        [Test]
        public void TextResultTest()
        {
            // TODO unit test for the property 'TextResult'
        }

    }

}
