/* 
 * ocrapi
 *
 * The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.OCR.Api;
using Cloudmersive.APIClient.NET.OCR.Model;
using Cloudmersive.APIClient.NET.OCR.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.OCR.Test
{
    /// <summary>
    ///  Class for testing OcrPageResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OcrPageResultTests
    {
        // TODO uncomment below to declare an instance variable for OcrPageResult
        //private OcrPageResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OcrPageResult
            //instance = new OcrPageResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OcrPageResult
        /// </summary>
        [Test]
        public void OcrPageResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OcrPageResult
            //Assert.IsInstanceOfType<OcrPageResult> (instance, "variable 'instance' is a OcrPageResult");
        }


        /// <summary>
        /// Test the property 'PageNumber'
        /// </summary>
        [Test]
        public void PageNumberTest()
        {
            // TODO unit test for the property 'PageNumber'
        }
        /// <summary>
        /// Test the property 'MeanConfidenceLevel'
        /// </summary>
        [Test]
        public void MeanConfidenceLevelTest()
        {
            // TODO unit test for the property 'MeanConfidenceLevel'
        }
        /// <summary>
        /// Test the property 'TextResult'
        /// </summary>
        [Test]
        public void TextResultTest()
        {
            // TODO unit test for the property 'TextResult'
        }

    }

}
