/* 
 * ocrapi
 *
 * The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.OCR.Api;
using Cloudmersive.APIClient.NET.OCR.Model;
using Cloudmersive.APIClient.NET.OCR.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.OCR.Test
{
    /// <summary>
    ///  Class for testing OcrPhotoTextElement
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OcrPhotoTextElementTests
    {
        // TODO uncomment below to declare an instance variable for OcrPhotoTextElement
        //private OcrPhotoTextElement instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OcrPhotoTextElement
            //instance = new OcrPhotoTextElement();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OcrPhotoTextElement
        /// </summary>
        [Test]
        public void OcrPhotoTextElementInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OcrPhotoTextElement
            //Assert.IsInstanceOfType<OcrPhotoTextElement> (instance, "variable 'instance' is a OcrPhotoTextElement");
        }


        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Test]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'XLeft'
        /// </summary>
        [Test]
        public void XLeftTest()
        {
            // TODO unit test for the property 'XLeft'
        }
        /// <summary>
        /// Test the property 'YTop'
        /// </summary>
        [Test]
        public void YTopTest()
        {
            // TODO unit test for the property 'YTop'
        }
        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Test]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }
        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Test]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }
        /// <summary>
        /// Test the property 'ConfidenceLevel'
        /// </summary>
        [Test]
        public void ConfidenceLevelTest()
        {
            // TODO unit test for the property 'ConfidenceLevel'
        }

    }

}
