/* 
 * ocrapi
 *
 * The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.OCR.Api;
using Cloudmersive.APIClient.NET.OCR.Model;
using Cloudmersive.APIClient.NET.OCR.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.OCR.Test
{
    /// <summary>
    ///  Class for testing OcrWordElement
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OcrWordElementTests
    {
        // TODO uncomment below to declare an instance variable for OcrWordElement
        //private OcrWordElement instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OcrWordElement
            //instance = new OcrWordElement();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OcrWordElement
        /// </summary>
        [Test]
        public void OcrWordElementInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OcrWordElement
            //Assert.IsInstanceOfType<OcrWordElement> (instance, "variable 'instance' is a OcrWordElement");
        }


        /// <summary>
        /// Test the property 'WordText'
        /// </summary>
        [Test]
        public void WordTextTest()
        {
            // TODO unit test for the property 'WordText'
        }
        /// <summary>
        /// Test the property 'LineNumber'
        /// </summary>
        [Test]
        public void LineNumberTest()
        {
            // TODO unit test for the property 'LineNumber'
        }
        /// <summary>
        /// Test the property 'WordNumber'
        /// </summary>
        [Test]
        public void WordNumberTest()
        {
            // TODO unit test for the property 'WordNumber'
        }
        /// <summary>
        /// Test the property 'XLeft'
        /// </summary>
        [Test]
        public void XLeftTest()
        {
            // TODO unit test for the property 'XLeft'
        }
        /// <summary>
        /// Test the property 'YTop'
        /// </summary>
        [Test]
        public void YTopTest()
        {
            // TODO unit test for the property 'YTop'
        }
        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Test]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }
        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Test]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }
        /// <summary>
        /// Test the property 'ConfidenceLevel'
        /// </summary>
        [Test]
        public void ConfidenceLevelTest()
        {
            // TODO unit test for the property 'ConfidenceLevel'
        }
        /// <summary>
        /// Test the property 'BlockNumber'
        /// </summary>
        [Test]
        public void BlockNumberTest()
        {
            // TODO unit test for the property 'BlockNumber'
        }
        /// <summary>
        /// Test the property 'ParagraphNumber'
        /// </summary>
        [Test]
        public void ParagraphNumberTest()
        {
            // TODO unit test for the property 'ParagraphNumber'
        }
        /// <summary>
        /// Test the property 'PageNumber'
        /// </summary>
        [Test]
        public void PageNumberTest()
        {
            // TODO unit test for the property 'PageNumber'
        }

    }

}
