/* 
 * ocrapi
 *
 * The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.OCR.Api;
using Cloudmersive.APIClient.NET.OCR.Model;
using Cloudmersive.APIClient.NET.OCR.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.OCR.Test
{
    /// <summary>
    ///  Class for testing ReceiptLineItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReceiptLineItemTests
    {
        // TODO uncomment below to declare an instance variable for ReceiptLineItem
        //private ReceiptLineItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReceiptLineItem
            //instance = new ReceiptLineItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReceiptLineItem
        /// </summary>
        [Test]
        public void ReceiptLineItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReceiptLineItem
            //Assert.IsInstanceOfType<ReceiptLineItem> (instance, "variable 'instance' is a ReceiptLineItem");
        }


        /// <summary>
        /// Test the property 'ItemDescription'
        /// </summary>
        [Test]
        public void ItemDescriptionTest()
        {
            // TODO unit test for the property 'ItemDescription'
        }
        /// <summary>
        /// Test the property 'ItemPrice'
        /// </summary>
        [Test]
        public void ItemPriceTest()
        {
            // TODO unit test for the property 'ItemPrice'
        }

    }

}
