/* 
 * ocrapi
 *
 * The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.OCR.Api;
using Cloudmersive.APIClient.NET.OCR.Model;
using Cloudmersive.APIClient.NET.OCR.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.OCR.Test
{
    /// <summary>
    ///  Class for testing ReceiptRecognitionResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReceiptRecognitionResultTests
    {
        // TODO uncomment below to declare an instance variable for ReceiptRecognitionResult
        //private ReceiptRecognitionResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReceiptRecognitionResult
            //instance = new ReceiptRecognitionResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReceiptRecognitionResult
        /// </summary>
        [Test]
        public void ReceiptRecognitionResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReceiptRecognitionResult
            //Assert.IsInstanceOfType<ReceiptRecognitionResult> (instance, "variable 'instance' is a ReceiptRecognitionResult");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Test]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'BusinessName'
        /// </summary>
        [Test]
        public void BusinessNameTest()
        {
            // TODO unit test for the property 'BusinessName'
        }
        /// <summary>
        /// Test the property 'BusinessWebsite'
        /// </summary>
        [Test]
        public void BusinessWebsiteTest()
        {
            // TODO unit test for the property 'BusinessWebsite'
        }
        /// <summary>
        /// Test the property 'AddressString'
        /// </summary>
        [Test]
        public void AddressStringTest()
        {
            // TODO unit test for the property 'AddressString'
        }
        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Test]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }
        /// <summary>
        /// Test the property 'ReceiptItems'
        /// </summary>
        [Test]
        public void ReceiptItemsTest()
        {
            // TODO unit test for the property 'ReceiptItems'
        }
        /// <summary>
        /// Test the property 'ReceiptTotal'
        /// </summary>
        [Test]
        public void ReceiptTotalTest()
        {
            // TODO unit test for the property 'ReceiptTotal'
        }

    }

}
