/* 
 * ocrapi
 *
 * The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.OCR.Api;
using Cloudmersive.APIClient.NET.OCR.Model;
using Cloudmersive.APIClient.NET.OCR.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.OCR.Test
{
    /// <summary>
    ///  Class for testing TableResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TableResultTests
    {
        // TODO uncomment below to declare an instance variable for TableResult
        //private TableResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TableResult
            //instance = new TableResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TableResult
        /// </summary>
        [Test]
        public void TableResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TableResult
            //Assert.IsInstanceOfType<TableResult> (instance, "variable 'instance' is a TableResult");
        }


        /// <summary>
        /// Test the property 'TableDefinition'
        /// </summary>
        [Test]
        public void TableDefinitionTest()
        {
            // TODO unit test for the property 'TableDefinition'
        }
        /// <summary>
        /// Test the property 'TableRowsResult'
        /// </summary>
        [Test]
        public void TableRowsResultTest()
        {
            // TODO unit test for the property 'TableRowsResult'
        }

    }

}
