/* 
 * ocrapi
 *
 * The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.OCR.Api;
using Cloudmersive.APIClient.NET.OCR.Model;
using Cloudmersive.APIClient.NET.OCR.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.OCR.Test
{
    /// <summary>
    ///  Class for testing TableCellResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TableCellResultTests
    {
        // TODO uncomment below to declare an instance variable for TableCellResult
        //private TableCellResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TableCellResult
            //instance = new TableCellResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TableCellResult
        /// </summary>
        [Test]
        public void TableCellResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TableCellResult
            //Assert.IsInstanceOfType<TableCellResult> (instance, "variable 'instance' is a TableCellResult");
        }


        /// <summary>
        /// Test the property 'ColumnID'
        /// </summary>
        [Test]
        public void ColumnIDTest()
        {
            // TODO unit test for the property 'ColumnID'
        }
        /// <summary>
        /// Test the property 'CellValues'
        /// </summary>
        [Test]
        public void CellValuesTest()
        {
            // TODO unit test for the property 'CellValues'
        }

    }

}
