/* 
 * ocrapi
 *
 * The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Cloudmersive.APIClient.NET.OCR.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NET.OCR.Model
{
    /// <summary>
    /// A single text in an OCR document
    /// </summary>
    [DataContract]
    public partial class OcrPhotoTextElement :  IEquatable<OcrPhotoTextElement>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OcrPhotoTextElement" /> class.
        /// </summary>
        /// <param name="Text">Text of the word.</param>
        /// <param name="XLeft">X location of the left edge of the word in pixels.</param>
        /// <param name="YTop">Y location of the top edge of the word in pixels.</param>
        /// <param name="Width">Width of the word in pixels.</param>
        /// <param name="Height">Height of the word in pixels.</param>
        /// <param name="ConfidenceLevel">Confidence level of the machine learning result; possible values are 0.0 (lowest accuracy) - 1.0 (highest accuracy).</param>
        public OcrPhotoTextElement(string Text = default(string), int? XLeft = default(int?), int? YTop = default(int?), int? Width = default(int?), int? Height = default(int?), double? ConfidenceLevel = default(double?))
        {
            this.Text = Text;
            this.XLeft = XLeft;
            this.YTop = YTop;
            this.Width = Width;
            this.Height = Height;
            this.ConfidenceLevel = ConfidenceLevel;
        }
        
        /// <summary>
        /// Text of the word
        /// </summary>
        /// <value>Text of the word</value>
        [DataMember(Name="Text", EmitDefaultValue=false)]
        public string Text { get; set; }

        /// <summary>
        /// X location of the left edge of the word in pixels
        /// </summary>
        /// <value>X location of the left edge of the word in pixels</value>
        [DataMember(Name="XLeft", EmitDefaultValue=false)]
        public int? XLeft { get; set; }

        /// <summary>
        /// Y location of the top edge of the word in pixels
        /// </summary>
        /// <value>Y location of the top edge of the word in pixels</value>
        [DataMember(Name="YTop", EmitDefaultValue=false)]
        public int? YTop { get; set; }

        /// <summary>
        /// Width of the word in pixels
        /// </summary>
        /// <value>Width of the word in pixels</value>
        [DataMember(Name="Width", EmitDefaultValue=false)]
        public int? Width { get; set; }

        /// <summary>
        /// Height of the word in pixels
        /// </summary>
        /// <value>Height of the word in pixels</value>
        [DataMember(Name="Height", EmitDefaultValue=false)]
        public int? Height { get; set; }

        /// <summary>
        /// Confidence level of the machine learning result; possible values are 0.0 (lowest accuracy) - 1.0 (highest accuracy)
        /// </summary>
        /// <value>Confidence level of the machine learning result; possible values are 0.0 (lowest accuracy) - 1.0 (highest accuracy)</value>
        [DataMember(Name="ConfidenceLevel", EmitDefaultValue=false)]
        public double? ConfidenceLevel { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OcrPhotoTextElement {\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  XLeft: ").Append(XLeft).Append("\n");
            sb.Append("  YTop: ").Append(YTop).Append("\n");
            sb.Append("  Width: ").Append(Width).Append("\n");
            sb.Append("  Height: ").Append(Height).Append("\n");
            sb.Append("  ConfidenceLevel: ").Append(ConfidenceLevel).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as OcrPhotoTextElement);
        }

        /// <summary>
        /// Returns true if OcrPhotoTextElement instances are equal
        /// </summary>
        /// <param name="input">Instance of OcrPhotoTextElement to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OcrPhotoTextElement input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Text == input.Text ||
                    (this.Text != null &&
                    this.Text.Equals(input.Text))
                ) && 
                (
                    this.XLeft == input.XLeft ||
                    (this.XLeft != null &&
                    this.XLeft.Equals(input.XLeft))
                ) && 
                (
                    this.YTop == input.YTop ||
                    (this.YTop != null &&
                    this.YTop.Equals(input.YTop))
                ) && 
                (
                    this.Width == input.Width ||
                    (this.Width != null &&
                    this.Width.Equals(input.Width))
                ) && 
                (
                    this.Height == input.Height ||
                    (this.Height != null &&
                    this.Height.Equals(input.Height))
                ) && 
                (
                    this.ConfidenceLevel == input.ConfidenceLevel ||
                    (this.ConfidenceLevel != null &&
                    this.ConfidenceLevel.Equals(input.ConfidenceLevel))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Text != null)
                    hashCode = hashCode * 59 + this.Text.GetHashCode();
                if (this.XLeft != null)
                    hashCode = hashCode * 59 + this.XLeft.GetHashCode();
                if (this.YTop != null)
                    hashCode = hashCode * 59 + this.YTop.GetHashCode();
                if (this.Width != null)
                    hashCode = hashCode * 59 + this.Width.GetHashCode();
                if (this.Height != null)
                    hashCode = hashCode * 59 + this.Height.GetHashCode();
                if (this.ConfidenceLevel != null)
                    hashCode = hashCode * 59 + this.ConfidenceLevel.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
