/* 
 * ocrapi
 *
 * The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Cloudmersive.APIClient.NET.OCR.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NET.OCR.Model
{
    /// <summary>
    /// Result of recognizing a receipt, to extract the key information from the receipt
    /// </summary>
    [DataContract]
    public partial class ReceiptRecognitionResult :  IEquatable<ReceiptRecognitionResult>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReceiptRecognitionResult" /> class.
        /// </summary>
        /// <param name="successful">True if the operation was successful, false otherwise.</param>
        /// <param name="timestamp">The date and time printed on the receipt (if included on the receipt).</param>
        /// <param name="businessName">The name of the business printed on the receipt (if included on the receipt).</param>
        /// <param name="businessWebsite">The website URL of the business printed on the receipt (if included on the receipt).</param>
        /// <param name="addressString">The address of the business printed on the receipt (if included on the receipt).</param>
        /// <param name="phoneNumber">The phone number printed on the receipt (if included on the receipt).</param>
        /// <param name="receiptItems">The individual line items comprising the order; does not include total (see ReceiptTotal).</param>
        /// <param name="receiptTotal">The total monetary value of the receipt (if included on the receipt).</param>
        public ReceiptRecognitionResult(bool? successful = default(bool?), DateTime? timestamp = default(DateTime?), string businessName = default(string), string businessWebsite = default(string), string addressString = default(string), string phoneNumber = default(string), List<ReceiptLineItem> receiptItems = default(List<ReceiptLineItem>), double? receiptTotal = default(double?))
        {
            this.Successful = successful;
            this.Timestamp = timestamp;
            this.BusinessName = businessName;
            this.BusinessWebsite = businessWebsite;
            this.AddressString = addressString;
            this.PhoneNumber = phoneNumber;
            this.ReceiptItems = receiptItems;
            this.ReceiptTotal = receiptTotal;
        }
        
        /// <summary>
        /// True if the operation was successful, false otherwise
        /// </summary>
        /// <value>True if the operation was successful, false otherwise</value>
        [DataMember(Name="Successful", EmitDefaultValue=false)]
        public bool? Successful { get; set; }

        /// <summary>
        /// The date and time printed on the receipt (if included on the receipt)
        /// </summary>
        /// <value>The date and time printed on the receipt (if included on the receipt)</value>
        [DataMember(Name="Timestamp", EmitDefaultValue=false)]
        public DateTime? Timestamp { get; set; }

        /// <summary>
        /// The name of the business printed on the receipt (if included on the receipt)
        /// </summary>
        /// <value>The name of the business printed on the receipt (if included on the receipt)</value>
        [DataMember(Name="BusinessName", EmitDefaultValue=false)]
        public string BusinessName { get; set; }

        /// <summary>
        /// The website URL of the business printed on the receipt (if included on the receipt)
        /// </summary>
        /// <value>The website URL of the business printed on the receipt (if included on the receipt)</value>
        [DataMember(Name="BusinessWebsite", EmitDefaultValue=false)]
        public string BusinessWebsite { get; set; }

        /// <summary>
        /// The address of the business printed on the receipt (if included on the receipt)
        /// </summary>
        /// <value>The address of the business printed on the receipt (if included on the receipt)</value>
        [DataMember(Name="AddressString", EmitDefaultValue=false)]
        public string AddressString { get; set; }

        /// <summary>
        /// The phone number printed on the receipt (if included on the receipt)
        /// </summary>
        /// <value>The phone number printed on the receipt (if included on the receipt)</value>
        [DataMember(Name="PhoneNumber", EmitDefaultValue=false)]
        public string PhoneNumber { get; set; }

        /// <summary>
        /// The individual line items comprising the order; does not include total (see ReceiptTotal)
        /// </summary>
        /// <value>The individual line items comprising the order; does not include total (see ReceiptTotal)</value>
        [DataMember(Name="ReceiptItems", EmitDefaultValue=false)]
        public List<ReceiptLineItem> ReceiptItems { get; set; }

        /// <summary>
        /// The total monetary value of the receipt (if included on the receipt)
        /// </summary>
        /// <value>The total monetary value of the receipt (if included on the receipt)</value>
        [DataMember(Name="ReceiptTotal", EmitDefaultValue=false)]
        public double? ReceiptTotal { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ReceiptRecognitionResult {\n");
            sb.Append("  Successful: ").Append(Successful).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  BusinessName: ").Append(BusinessName).Append("\n");
            sb.Append("  BusinessWebsite: ").Append(BusinessWebsite).Append("\n");
            sb.Append("  AddressString: ").Append(AddressString).Append("\n");
            sb.Append("  PhoneNumber: ").Append(PhoneNumber).Append("\n");
            sb.Append("  ReceiptItems: ").Append(ReceiptItems).Append("\n");
            sb.Append("  ReceiptTotal: ").Append(ReceiptTotal).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ReceiptRecognitionResult);
        }

        /// <summary>
        /// Returns true if ReceiptRecognitionResult instances are equal
        /// </summary>
        /// <param name="input">Instance of ReceiptRecognitionResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReceiptRecognitionResult input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Successful == input.Successful ||
                    (this.Successful != null &&
                    this.Successful.Equals(input.Successful))
                ) && 
                (
                    this.Timestamp == input.Timestamp ||
                    (this.Timestamp != null &&
                    this.Timestamp.Equals(input.Timestamp))
                ) && 
                (
                    this.BusinessName == input.BusinessName ||
                    (this.BusinessName != null &&
                    this.BusinessName.Equals(input.BusinessName))
                ) && 
                (
                    this.BusinessWebsite == input.BusinessWebsite ||
                    (this.BusinessWebsite != null &&
                    this.BusinessWebsite.Equals(input.BusinessWebsite))
                ) && 
                (
                    this.AddressString == input.AddressString ||
                    (this.AddressString != null &&
                    this.AddressString.Equals(input.AddressString))
                ) && 
                (
                    this.PhoneNumber == input.PhoneNumber ||
                    (this.PhoneNumber != null &&
                    this.PhoneNumber.Equals(input.PhoneNumber))
                ) && 
                (
                    this.ReceiptItems == input.ReceiptItems ||
                    this.ReceiptItems != null &&
                    this.ReceiptItems.SequenceEqual(input.ReceiptItems)
                ) && 
                (
                    this.ReceiptTotal == input.ReceiptTotal ||
                    (this.ReceiptTotal != null &&
                    this.ReceiptTotal.Equals(input.ReceiptTotal))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Successful != null)
                    hashCode = hashCode * 59 + this.Successful.GetHashCode();
                if (this.Timestamp != null)
                    hashCode = hashCode * 59 + this.Timestamp.GetHashCode();
                if (this.BusinessName != null)
                    hashCode = hashCode * 59 + this.BusinessName.GetHashCode();
                if (this.BusinessWebsite != null)
                    hashCode = hashCode * 59 + this.BusinessWebsite.GetHashCode();
                if (this.AddressString != null)
                    hashCode = hashCode * 59 + this.AddressString.GetHashCode();
                if (this.PhoneNumber != null)
                    hashCode = hashCode * 59 + this.PhoneNumber.GetHashCode();
                if (this.ReceiptItems != null)
                    hashCode = hashCode * 59 + this.ReceiptItems.GetHashCode();
                if (this.ReceiptTotal != null)
                    hashCode = hashCode * 59 + this.ReceiptTotal.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
